### ISSUE TITLE
SnipCart Error Add to Cart not working

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-skeleton-shop-site#2]
I have downloaded the skeleton and after loading the page I'm getting this error.
`Uncaught TypeError: Snipcart.get(...) is not a function` at `snipcart.js:8`

**Comment by couellet** [comment]
Did you add your API key correctly? Would be helpful if you could paste the source of the page with Snipcart assets to make sure everything is added correctly.

**Comment by phystem** [comment]
Where should the API key be present.I dont see any api key.I simply downloaded the skeleton from [here](https://getgrav.org/downloads/skeletons) follwing the instructions mentioned there 

> Simply download the ZIP file, extract it in your web-

and what do you mean by source of the page and I'm using it as zip not using git install

**Comment by ghost** [comment]
Sorry My mistake havent read the usage of snipcart..from [https://github.com/getgrav/grav-plugin-snipcart#usage](https://github.com/getgrav/grav-plugin-snipcart#usage).You can close this
