### ISSUE TITLE
Shopping Cart compatibility

### ISSUE THREAD

**Issue by kamaleshdubey** [getgrav/grav-skeleton-shop-site#4]
Does this shopping cart work only with SnipCart or will it also work with the Shopping Cart plugin available for Grav? #

**Comment by flaviocopes** [comment]
This skeleton is a site example built on the SnipCart Plugin.

It's "compatible" which means you can disable one plugin and enable the other, but the pages structure will need to be changed to suit https://gravcart.com/docs/pages-structure

**Comment by kamaleshdubey** [comment]
Sorry @flaviocopes one other query that I had is does this theme support self-registration of shoppers making a purchase or does it need some add-on development/pugin?

**Comment by flaviocopes** [comment]
Currently there is no integration with the Login system. That is a good idea for an addon.
