### ISSUE TITLE
Server error installing skeleton theme

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-skeleton-shop-site#8]
First time visiting the site after installing gives a server error.

`0 - syntax error, unexpected '=', expecting ']'`

This is in the logs:

`[2021-11-27 12:40:54] grav.CRITICAL: syntax error, unexpected '=', expecting ']' - Trace: #0 /home/simplyco/public_html/themes/shopsite/vendor/rockettheme/toolbox/File/src/AbstractFile.php(303): RocketTheme\Toolbox\File\PhpFile->decode('<?php\nreturn [\n...') #1 /home/simplyco/public_html/themes/shopsite/vendor/rockettheme/toolbox/File/src/File.php(24): RocketTheme\Toolbox\File\AbstractFile->content(NULL) #2 /home/simplyco/public_html/themes/shopsite/vendor/rockettheme/toolbox/File/src/PhpFile.php(27): RocketTheme\Toolbox\File\File->content(NULL) #3 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/File/CompiledFile.php(50): RocketTheme\Toolbox\File\PhpFile->content() #4 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Config/CompiledLanguages.php(79): Grav\Common\File\CompiledYamlFile->content() #5 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Config/CompiledBase.php(180): Grav\Common\Config\CompiledLanguages->loadFile('tr', '/home/simplyco/...') #6 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Config/CompiledBase.php(112): Grav\Common\Config\CompiledBase->loadFiles() #7 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Service/ConfigServiceProvider.php(172): Grav\Common\Config\CompiledBase->load() #8 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Service/ConfigServiceProvider.php(74): Grav\Common\Service\ConfigServiceProvider::languages(Object(Grav\Common\Grav)) #9 /home/simplyco/public_html/themes/shopsite/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #10 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Themes.php(353): Pimple\Container->offsetGet('languages') #11 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Themes.php(321): Grav\Common\Themes->loadLanguages(Object(Grav\Common\Config\Config)) #12 /home/simplyco/public_html/themes/shopsite/user/plugins/admin/classes/plugin/Themes.php(17): Grav\Common\Themes->configure() #13 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Processors/ThemesProcessor.php(35): Grav\Plugin\Admin\Themes->init() #14 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #15 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #18 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #21 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #22 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #23 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /home/simplyco/public_html/themes/shopsite/system/src/Grav/Common/Grav.php(303): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /home/simplyco/public_html/themes/shopsite/index.php(58): Grav\Common\Grav->process() #26 {main} [] []`

**Comment by rhukster** [comment]
I don't get an error like this.

**Comment by ghost** [comment]
I loaded up 12 skeleton themes yesterday into 12 separate folders in the same account, so I could play around with them. Two of them gave this error, so am assuming it wasn't something on my server that was causing it.

I will delete and try again and see if I can replicate.

**Comment by ghost** [comment]
Hmmm... the second time I get a different error message.
![error](https://user-images.githubusercontent.com/46998578/143722980-a9dcf5c6-7a06-439a-a5de-de0d84df798e.jpg)

The third time it worked normally. I guess it must be something random at my end.

**Comment by ghost** [comment]
Closing this as it is now working.
